### ISSUE TITLE
Add account

### ISSUE THREAD

**Issue by Pontare25** [DIT212-Alpha/DIT212-Alpha#12]
## Description 
As a user, I need to register an account so that I can interact with the application.

### Functional
- [x] Username is unique
- [x] Firstname and surname are filled in.
- [x] The user is registered
- [x] Sign-in and register nice looking prototypes 
- [x] register and sign-in with Google
- [ ] register and sign-in with Facebook 
- [x] register and sign-in with email and password 
- [x] Authentication via database
- [x] The login screen is shown if the user is not logged in
- [x] When a user successfully logs in the home screen is shown
- [x] If the user is already logged in when the app starts, the map screen is displayed immediately

## Tasks
- [x] Comment code
- [x] Document in domain/design model

## Assignees
- @Bashar3
