### ISSUE TITLE
See broadcasts on map

### ISSUE THREAD

**Issue by Pontare25** [DIT212-Alpha/DIT212-Alpha#14]
## Description 
As a user, I want to see where related broadcasts are located in relation to myself so that I can choose to join them.

### Functional
- [x] Can the user see active broadcasts with a dot on the map?
- [x] Can the user press the broadcast to show the broadcast's course?

## Tasks
- [x] Load Broadcast information from "database"
- [x] Display Broadcast as a dot on Map using its GPS information
- [x] When the Broadcast dot is pressed display the Broadcast description in a window
- [x] Create a Broadcast information window containing Course and Description
- [x] Comment code @Sannholm 
- [x] Document in domain/design model  @Sannholm

## Assignee
- @sophiapham 
- @Bashar3 
- @Sannholm
