### ISSUE TITLE
Create broadcast study session

### ISSUE THREAD

**Issue by sophiapham** [DIT212-Alpha/DIT212-Alpha#2]
## Description 
As a user I want to broadcast that I'm looking for a study partner so that others can join me.

### Functional
- [x] Can the user add a broadcast?
- [x] Does the location of the user issuing the broadcast get saved?
- [x] Does the course the user entered get saved?
- [x] Does the description the user entered get saved?

## Tasks
- [x] Add a addBroadcastWindow
- [x]  Add a button titled "Broadcast" that takes the user to a new screen for creating a broadcast @Bashar3 
- [x] Add a dropdown-list (field) to select a course for the broadcast
- [x] Add a field for a description of the broadcast
- [x] Collect the users GPS data (position) and add them to the broadcast @drage1994 
- [x] Add a button to save/confirm the broadcast
- [x] Add a button to cancel creating the broadcast.
- [x] Save the broadcast to the "database"  @drage1994
- [x] Comment code
- [x] Document in domain/design model

## Assignees
- @Pontare25 
- @drage1994 
- @Bashar3
