### ISSUE TITLE
Select Course to filter on

### ISSUE THREAD

**Issue by Pontare25** [DIT212-Alpha/DIT212-Alpha#3]
## Description 
As a user, I want to select a course to filter the map on so that I can see relevant broadcasts
### Functional
- [x] Users can only see broadcasts related to the same courses they have selected.
- [x] The user can select what courses should be visible using a UI.

## Tasks
- [x] Comment code
- [x] Document in domain/design model

## Assignees
- @Bashar3
