### ISSUE TITLE
Only the same broadcast creator should be able to edit his own broadcast

### ISSUE THREAD

**Issue by sophiapham** [DIT212-Alpha/DIT212-Alpha#35]
## Description 
As a user I do not want other users to be able to edit my broadcasts so they do no mess up my study session.

### Non-functional
- [x] Each broadcast is associated with its owner.
- [x] The edit button on a broadcast is only shown to the user who owns it.

## Tasks
- [x] Comment code
- [x] Document in domain/design model

## Assignees
- @drage1994
