### ISSUE TITLE
See Map

### ISSUE THREAD

**Issue by Pontare25** [DIT212-Alpha/DIT212-Alpha#4]
## Description 
As a user, I want to view the map so that I can see where I am.

### Functional
- [x] Can the user see the map?
- [x] The user should be able to see a dot of where he/she is on a map.
- [x] When the map initially shows, is the map centred on the user's location?
- [x] When the user swipes on the screen the map pans accordingly

## Tasks
- [x] Create a window displaying the Google Maps API
- [x] Load the user's GPS information
- [x] Display the users GPS position as a dot on the map
- [x] Refactor MapsActivity into map display part @Sannholm
- [x] Refactor MapsActivity into geo-location service @drage1994
- [x] Refactor MapsActivity into database storage part @Bashar3
- [x] Comment code @Sannholm
- [x] Document in domain/design model @Sannholm
