### ISSUE TITLE
Edit existing broadcast

### ISSUE THREAD

**Issue by Pontare25** [DIT212-Alpha/DIT212-Alpha#6]
## Description 
As a user, I want to edit my broadcast so that I can change the subject studied, the description, and the timer. 

### Functional
- [x] The broadcast should be updated for all users seeing it.
- [x] There should be an edit button on the description info window.
- [x] It should be possible to edit the description box.

### Non-functional
- [x] Only the creator of the broadcast should be able to edit the broadcast.

## Tasks
- [x] Comment code
- [x] Document in domain/design model

## Assignees
- @sophiapham
