### ISSUE TITLE
Terminate broadcast if the user leaves the area.

### ISSUE THREAD

**Issue by sophiapham** [DIT212-Alpha/DIT212-Alpha#9]
## Description 
As a user I want the broadcast to self-terminate if I walk too far from the designated area.

### Functional
- [x] If the user that made the broadcast goes too far from the designated area the broadcast is terminated.

### Non-functional
- [x] Once the broadcast has been terminated it will not show up again if the area is entered.
- [x] Only the user who created the broadcast affects its termination.

## Tasks
- [x] Comment code
- [x] Document in domain/design model

## Assignees
- @Sannholm
